// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdkuuzhupothejryywzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNka3V1emh1cG90aGVqcnl5d3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTUyNDYsImV4cCI6MjA1OTQzMTI0Nn0.mQmQsydpKpYjhhIsnXNtk9vc3TCBDAopraj0Tn0Inn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);